services:
  app:
    image: node:18
    working_dir: /app
    # Mount the project into the container so edits are visible immediately
    volumes:
      - ./:/app:delegated
      # Use a named volume for node_modules so the host's node_modules doesn't
      # conflict with the container's environment.
      - dev_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 5000
      HOST: 0.0.0.0
    ports:
      - "5000:5000"   # server
      - "5173:5173"   # Vite dev server / HMR
    command: sh -c "npm install --no-audit --no-fund --silent || true && npm run dev"
    # no depends_on; using Atlas for MongoDB

volumes:
  dev_node_modules:
